/**
 * System Constants for Clinical Logic, ICD-10, Lab Thresholds, and Status Enums
 */

module.exports = {
  ENCOUNTER_TYPES: {
    OUTPATIENT_VISIT: 'OUTPATIENT_VISIT',
    INPATIENT_ADMISSION: 'INPATIENT_ADMISSION',
    EMERGENCY_TRIAGE: 'EMERGENCY_TRIAGE',
    TELEHEALTH_CONSULTATION: 'TELEHEALTH_CONSULTATION',
    ROUTINE_CHECKUP: 'ROUTINE_CHECKUP',
    SPECIALIST_CONSULTATION: 'SPECIALIST_CONSULTATION',
    POST_OPERATIVE_FOLLOWUP: 'POST_OPERATIVE_FOLLOWUP'
  },

  ENCOUNTER_STATUSES: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    TRIAGED: 'TRIAGED',
    AWAITING_LABS: 'AWAITING_LABS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW'
  },

  APPOINTMENT_STATUSES: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    CHECKED_IN: 'CHECKED_IN',
    IN_CONSULTATION: 'IN_CONSULTATION',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    RESCHEDULED: 'RESCHEDULED'
  },

  PRESCRIPTION_STATUSES: {
    ACTIVE: 'ACTIVE',
    DISPENSED: 'DISPENSED',
    PARTIALLY_DISPENSED: 'PARTIALLY_DISPENSED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED',
    DISCONTINUED: 'DISCONTINUED'
  },

  LAB_STATUSES: {
    ORDERED: 'ORDERED',
    COLLECTED: 'COLLECTED',
    IN_ANALYSIS: 'IN_ANALYSIS',
    PRELIMINARY_RESULTS: 'PRELIMINARY_RESULTS',
    FINALIZED: 'FINALIZED',
    VERIFIED: 'VERIFIED',
    CRITICAL_ALERT: 'CRITICAL_ALERT',
    CANCELLED: 'CANCELLED'
  },

  BILLING_STATUSES: {
    DRAFT: 'DRAFT',
    PENDING_SUBMISSION: 'PENDING_SUBMISSION',
    CLAIM_SUBMITTED: 'CLAIM_SUBMITTED',
    ADJUDICATION_PENDING: 'ADJUDICATION_PENDING',
    PAID_IN_FULL: 'PAID_IN_FULL',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    DENIED: 'DENIED',
    APPEALED: 'APPEALED',
    WRITTEN_OFF: 'WRITTEN_OFF'
  },

  TRIAGE_LEVELS: {
    ESI_1_RESUSCITATION: { level: 1, name: 'Resuscitation (Immediate)', color: '#dc2626', targetMinutes: 0 },
    ESI_2_EMERGENT: { level: 2, name: 'Emergent (High Risk)', color: '#ea580c', targetMinutes: 10 },
    ESI_3_URGENT: { level: 3, name: 'Urgent (Moderate Risk)', color: '#ca8a04', targetMinutes: 30 },
    ESI_4_LESS_URGENT: { level: 4, name: 'Less Urgent (Low Risk)', color: '#16a34a', targetMinutes: 60 },
    ESI_5_NON_URGENT: { level: 5, name: 'Non-Urgent (Routine)', color: '#2563eb', targetMinutes: 120 }
  },

  CDS_ALERT_SEVERITIES: {
    INFO: 'INFO',
    LOW: 'LOW',
    MODERATE: 'MODERATE',
    HIGH: 'HIGH',
    CRITICAL_CONTRAINDICATION: 'CRITICAL_CONTRAINDICATION'
  }
};
