/**
 * Role-Based Access Control (RBAC) Permissions Matrix
 * Defines granular capabilities across 7 clinical and administrative roles.
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CHIEF_MEDICAL_OFFICER: 'CHIEF_MEDICAL_OFFICER',
  ATTENDING_PHYSICIAN: 'ATTENDING_PHYSICIAN',
  RESIDENT_DOCTOR: 'RESIDENT_DOCTOR',
  REGISTERED_NURSE: 'REGISTERED_NURSE',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  PHARMACIST: 'PHARMACIST',
  BILLING_SPECIALIST: 'BILLING_SPECIALIST',
  PATIENT: 'PATIENT'
};

const PERMISSIONS = {
  // Patient Demographics & Records
  PATIENTS_VIEW: 'patients:view',
  PATIENTS_CREATE: 'patients:create',
  PATIENTS_EDIT: 'patients:edit',
  PATIENTS_DELETE: 'patients:delete',
  PATIENTS_EXPORT: 'patients:export',

  // Clinical Encounters & SOAP Notes
  ENCOUNTERS_VIEW: 'encounters:view',
  ENCOUNTERS_CREATE: 'encounters:create',
  ENCOUNTERS_SIGN: 'encounters:sign',
  ENCOUNTERS_EDIT: 'encounters:edit',

  // Electronic Prescriptions (e-Rx)
  RX_VIEW: 'prescriptions:view',
  RX_PRESCRIBE: 'prescriptions:prescribe',
  RX_DISPENSE: 'prescriptions:dispense',
  RX_CANCEL: 'prescriptions:cancel',

  // Pathology & Diagnostic Labs
  LABS_VIEW: 'labs:view',
  LABS_ORDER: 'labs:order',
  LABS_ENTER_RESULTS: 'labs:enter_results',
  LABS_VERIFY: 'labs:verify',

  // Appointments & Schedules
  APPOINTMENTS_VIEW: 'appointments:view',
  APPOINTMENTS_SCHEDULE: 'appointments:schedule',
  APPOINTMENTS_CANCEL: 'appointments:cancel',
  APPOINTMENTS_MANAGE_SLOTS: 'appointments:manage_slots',

  // Telehealth & Video Consultations
  TELEHEALTH_JOIN: 'telehealth:join',
  TELEHEALTH_HOST: 'telehealth:host',
  TELEHEALTH_RECORD: 'telehealth:record',

  // Medical Billing & Insurance Claims
  BILLING_VIEW: 'billing:view',
  BILLING_CREATE_INVOICE: 'billing:create_invoice',
  BILLING_SUBMIT_CLAIM: 'billing:submit_claim',
  BILLING_PROCESS_PAYMENT: 'billing:process_payment',

  // Pharmacy & Formulary
  PHARMACY_INVENTORY_VIEW: 'pharmacy:inventory_view',
  PHARMACY_INVENTORY_MANAGE: 'pharmacy:inventory_manage',

  // Triage & Bed Allocation
  TRIAGE_ASSESS: 'triage:assess',
  BED_ALLOCATE: 'bed:allocate',

  // Clinical Decision Support & CDS Alerts
  CDS_OVERRIDE_ALERT: 'cds:override_alert',
  CDS_CONFIGURE_RULES: 'cds:configure_rules',

  // System Administration & HIPAA Audit Logs
  AUDIT_LOGS_VIEW: 'audit:view',
  USERS_MANAGE: 'users:manage',
  SYSTEM_CONFIG: 'system:config'
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.CHIEF_MEDICAL_OFFICER]: Object.values(PERMISSIONS).filter(p => p !== PERMISSIONS.USERS_MANAGE),
  [ROLES.ATTENDING_PHYSICIAN]: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT, PERMISSIONS.PATIENTS_EXPORT,
    PERMISSIONS.ENCOUNTERS_VIEW, PERMISSIONS.ENCOUNTERS_CREATE, PERMISSIONS.ENCOUNTERS_SIGN, PERMISSIONS.ENCOUNTERS_EDIT,
    PERMISSIONS.RX_VIEW, PERMISSIONS.RX_PRESCRIBE, PERMISSIONS.RX_CANCEL,
    PERMISSIONS.LABS_VIEW, PERMISSIONS.LABS_ORDER, PERMISSIONS.LABS_VERIFY,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_SCHEDULE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.TELEHEALTH_JOIN, PERMISSIONS.TELEHEALTH_HOST,
    PERMISSIONS.TRIAGE_ASSESS, PERMISSIONS.BED_ALLOCATE,
    PERMISSIONS.CDS_OVERRIDE_ALERT,
    PERMISSIONS.BILLING_VIEW
  ],
  [ROLES.RESIDENT_DOCTOR]: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.ENCOUNTERS_VIEW, PERMISSIONS.ENCOUNTERS_CREATE, PERMISSIONS.ENCOUNTERS_EDIT,
    PERMISSIONS.RX_VIEW, PERMISSIONS.RX_PRESCRIBE,
    PERMISSIONS.LABS_VIEW, PERMISSIONS.LABS_ORDER,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_SCHEDULE,
    PERMISSIONS.TELEHEALTH_JOIN, PERMISSIONS.TELEHEALTH_HOST,
    PERMISSIONS.TRIAGE_ASSESS, PERMISSIONS.BED_ALLOCATE,
    PERMISSIONS.BILLING_VIEW
  ],
  [ROLES.REGISTERED_NURSE]: [
    PERMISSIONS.PATIENTS_VIEW, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.ENCOUNTERS_VIEW,
    PERMISSIONS.RX_VIEW,
    PERMISSIONS.LABS_VIEW, PERMISSIONS.LABS_ORDER,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_SCHEDULE,
    PERMISSIONS.TELEHEALTH_JOIN,
    PERMISSIONS.TRIAGE_ASSESS, PERMISSIONS.BED_ALLOCATE
  ],
  [ROLES.LAB_TECHNICIAN]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.LABS_VIEW, PERMISSIONS.LABS_ENTER_RESULTS, PERMISSIONS.LABS_VERIFY
  ],
  [ROLES.PHARMACIST]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.RX_VIEW, PERMISSIONS.RX_DISPENSE,
    PERMISSIONS.PHARMACY_INVENTORY_VIEW, PERMISSIONS.PHARMACY_INVENTORY_MANAGE
  ],
  [ROLES.BILLING_SPECIALIST]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE_INVOICE,
    PERMISSIONS.BILLING_SUBMIT_CLAIM, PERMISSIONS.BILLING_PROCESS_PAYMENT,
    PERMISSIONS.ENCOUNTERS_VIEW
  ],
  [ROLES.PATIENT]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.ENCOUNTERS_VIEW,
    PERMISSIONS.RX_VIEW,
    PERMISSIONS.LABS_VIEW,
    PERMISSIONS.APPOINTMENTS_VIEW, PERMISSIONS.APPOINTMENTS_SCHEDULE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.TELEHEALTH_JOIN,
    PERMISSIONS.BILLING_VIEW
  ]
};

function hasPermission(userRole, requiredPermission) {
  if (!userRole) return false;
  if (userRole === ROLES.SUPER_ADMIN) return true;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(requiredPermission);
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
